return function(apps)
    local mod = "SUPER"
    local function bind(keys, dispatcher, options)
        hl.bind(keys, dispatcher, options)
    end
    local function exec(keys, command, options)
        bind(keys, hl.dsp.exec_cmd(command), options)
    end

    exec(mod .. " + RETURN", apps.terminal)
    exec(mod .. " + E", apps.file_manager)
    exec(mod .. " + PRINT", apps.screenshot)
    exec("PRINT", "hyprshot -m region")
    bind(mod .. " + Q", hl.dsp.window.close())
    exec(mod .. " + SHIFT + M", 'loginctl terminate-user ""')
    bind(mod .. " + V", hl.dsp.window.float({ action = "toggle" }))
    exec(mod .. " + SPACE", apps.launcher)
    bind(mod .. " + F", hl.dsp.window.fullscreen())
    bind(mod .. " + Y", hl.dsp.window.pin({ action = "toggle" }))
    bind(mod .. " + J", hl.dsp.layout("togglesplit"))

    exec("F8", "gromit-mpx --undo")
    exec("SHIFT + F8", "gromit-mpx --redo")
    exec(mod .. " + C", "zen-browser")
    exec(mod .. " + Z", "neovide")
    exec(mod .. " + X", "powermenu")
    exec(mod .. " + A", "~/.local/bin/toggle-obsidian.sh")
    exec("ALT + SHIFT + bracketright", "~/.local/bin/monitor-brightness.sh inc 10", { locked = true, repeating = true })
    exec("ALT + SHIFT + bracketleft", "~/.local/bin/monitor-brightness.sh dec 10", { locked = true, repeating = true })

    bind(mod .. " + l", hl.dsp.window.resize({ x = 50, y = 0, relative = true }))
    bind(mod .. " + h", hl.dsp.window.resize({ x = -50, y = 0, relative = true }))
    bind(mod .. " + SHIFT + k", hl.dsp.window.resize({ x = 0, y = -50, relative = true }))
    bind(mod .. " + SHIFT + j", hl.dsp.window.resize({ x = 0, y = 50, relative = true }))
    bind(mod .. " + k", hl.dsp.window.cycle_next())
    bind(mod .. " + j", hl.dsp.window.cycle_next({ next = false }))
    exec(mod .. " + B", "killall waybar || $HOME/.local/bin/waybar")
    bind(mod .. " + SHIFT + G", function()
        hl.config({ general = { gaps_out = 5, gaps_in = 3 } })
    end)
    bind(mod .. " + G", function()
        hl.config({ general = { gaps_out = 0, gaps_in = 0 } })
    end)

    exec(mod .. " + bracketright", "pulsemixer --change-volume +5", { locked = true, repeating = true })
    exec(mod .. " + bracketleft", "pulsemixer --change-volume -5", { locked = true, repeating = true })
    exec(mod .. " + backslash", "amixer sset Master toggle | sed -En '/\\[on\\]/ s/.*\\[([0-9]+)%\\].*/\\1/ p; /\\[off\\]/ s/.*/0/p' | head -1 > /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob", { locked = true, repeating = true })
    exec("ALT + bracketright", "playerctl next", { locked = true, repeating = true })
    exec("ALT + bracketleft", "playerctl previous", { locked = true, repeating = true })
    exec("ALT + backslash", "playerctl play-pause", { locked = true, repeating = true })
    exec("XF86AudioPlay", "playerctl play-pause")
    exec("XF86AudioNext", "playerctl next")
    exec("XF86AudioPrev", "playerctl previous")
    exec("XF86MonBrightnessUp", "brightnessctl s +5%", { locked = true, repeating = true })
    exec("XF86MonBrightnessDown", "brightnessctl s 5%-", { locked = true, repeating = true })
    exec(mod .. " + SHIFT + P", "gnome-calculator")
    exec(mod .. " + O", "killall -SIGUSR2 waybar")

    bind("ALT + Tab", hl.dsp.window.cycle_next(), { repeating = true })
    bind(mod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
    bind(mod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })
    bind(mod .. " + SHIFT + left", hl.dsp.window.move({ direction = "left" }))
    bind(mod .. " + SHIFT + right", hl.dsp.window.move({ direction = "right" }))
    bind(mod .. " + SHIFT + up", hl.dsp.window.move({ direction = "up" }))
    bind(mod .. " + SHIFT + down", hl.dsp.window.move({ direction = "down" }))
    bind(mod .. " + left", hl.dsp.focus({ direction = "left" }))
    bind(mod .. " + right", hl.dsp.focus({ direction = "right" }))
    bind(mod .. " + up", hl.dsp.focus({ direction = "up" }))
    bind(mod .. " + down", hl.dsp.focus({ direction = "down" }))
    bind(mod .. " + SHIFT + RETURN", hl.dsp.layout("swapwithmaster"))
    bind("CTRL + grave", hl.dsp.pass({ window = "class:^(Discord)$" }), { non_consuming = true })

    for _, key in ipairs({ "right", "left", "up", "down", "l", "h", "k", "j" }) do
        local dx = (key == "right" or key == "l") and 15 or (key == "left" or key == "h") and -15 or 0
        local dy = (key == "down" or key == "j") and 15 or (key == "up" or key == "k") and -15 or 0
        bind(mod .. " + CTRL + SHIFT + " .. key, hl.dsp.window.resize({ x = dx, y = dy, relative = true }))
    end

    for i = 1, 10 do
        local key = i % 10
        bind(mod .. " + CTRL + " .. key, hl.dsp.window.move({ workspace = i }))
        bind(mod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = i, follow = false }))
        bind(mod .. " + " .. key, hl.dsp.focus({ workspace = i }))
    end
    bind(mod .. " + CTRL + left", hl.dsp.window.move({ workspace = -1 }))
    bind(mod .. " + CTRL + right", hl.dsp.window.move({ workspace = 1 }))
    bind(mod .. " + PERIOD", hl.dsp.focus({ workspace = "e+1" }))
    bind(mod .. " + COMMA", hl.dsp.focus({ workspace = "e-1" }))
    bind(mod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
    bind(mod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
    bind(mod .. " + Tab", hl.dsp.focus({ workspace = "previous" }))
    bind(mod .. " + minus", hl.dsp.window.move({ workspace = "special" }))
    bind(mod .. " + equal", hl.dsp.workspace.toggle_special(""))
    bind(mod .. " + F1", hl.dsp.workspace.toggle_special("scratchpad"))
    bind(mod .. " + SHIFT + F1", hl.dsp.window.move({ workspace = "special:scratchpad", follow = false }))
    exec(mod .. " + SHIFT + F", "~/.config/hypr/scripts/focusmode")
    exec(mod .. " + SHIFT + T", "~/.config/hypr/scripts/theme_toggle")
    exec("CTRL + grave", "equibop --toggle-mic")
    bind(mod .. " + SHIFT + space", hl.dsp.window.float({ action = "toggle" }))
end
