return function(colors, apps)
    local function rule(match, effects)
        effects.match = match
        hl.window_rule(effects)
    end

    rule({ class = "^(rofi)$" }, { float = true })
    rule({ class = "^(org.pulseaudio.pavucontrol)$" }, { float = true })
    rule({ class = "^$", title = "^(Picture in picture)$" }, { float = true })
    rule({ class = "^$", title = "^(Save File)$" }, { float = true })
    rule({ class = "^$", title = "^(Open File)$" }, { float = true })
    rule({ class = "^(LibreWolf)$", title = "^(Picture-in-Picture)$" }, { float = true })
    rule({ class = "^(blueman-manager)$" }, { float = true })
    rule({ class = "^(xdg-desktop-portal-gtk|xdg-desktop-portal-kde|xdg-desktop-portal-hyprland)(.*)$" }, { float = true })
    rule({ class = "^(polkit-gnome-authentication-agent-1|hyprpolkitagent|org.org.kde.polkit-kde-authentication-agent-1)(.*)$" }, { float = true })
    rule({ class = "^(CachyOSHello)$" }, { float = true })
    rule({ class = "^(zenity)$" }, { float = true })
    rule({ class = "^$", title = "^(Steam - Self Updater)$" }, { float = true })
    -- Keep the screen-share source picker compact and centered on every use.
    rule({ class = "^(hyprland-share-picker)$" }, { float = true, size = "960 540", center = true })

    rule({ title = "^(Picture-in-Picture)$" }, { float = true, size = "960 540", move = "25%- 25%-" })
    rule({ title = "^(imv|mpv|danmufloat|termfloat|nemo|ncmpcpp)$" }, { float = true, move = "25%- 25%-", size = "960 540" })
    rule({ title = "^(danmufloat)$" }, { pin = true })
    rule({ title = "^(danmufloat|termfloat)$" }, { rounding = 5 })
    rule({ class = "^(zen)$" }, { no_blur = true })
    rule({ class = "^(equibop)$" }, { no_blur = true })
    rule({ class = "^(obsidian)$" }, { opacity = "0.85 0.85" })
    rule({ float = true, workspace = "w[fv1-10]" }, { border_size = 2, border_color = colors.blue_light, rounding = 8 })
    rule({ float = false, workspace = "f[1-10]" }, { border_size = 3, rounding = 4 })
    rule({ class = "^(virt-manager)$" }, { opacity = "0.999 0.999" })
    rule({ class = "^(virt-viewer)$" }, { opacity = "0.999 0.999" })
    rule({ class = "zoom", title = "menu window" }, { stay_focused = true })
    rule({ class = "zoom" }, { no_blur = true })
    rule({ title = "as_toolbar" }, { no_blur = true })

    hl.workspace_rule({ workspace = "1", default_name = "󰖟   browser", persistent = true })
    hl.workspace_rule({ workspace = "2", default_name = "   code", persistent = true })
    hl.workspace_rule({ workspace = "3", default_name = "   discord", persistent = true })
    hl.workspace_rule({ workspace = "4", default_name = "♫   music", persistent = true })
    hl.workspace_rule({ workspace = "r[1-5]", monitor = "DP-2" })
    hl.workspace_rule({ workspace = "special:scratchpad", on_created_empty = apps.launcher })
    hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
    hl.workspace_rule({ workspace = "f[1]", gaps_out = 0, gaps_in = 0 })
    rule({ float = false, workspace = "w[tv1]" }, { border_size = 0, rounding = 0 })
    rule({ float = false, workspace = "f[1]" }, { border_size = 0, rounding = 0 })

    hl.layer_rule({ match = { namespace = "logout_dialog" }, animation = "slide top" })
    hl.layer_rule({ match = { namespace = "waybar" }, animation = "slide down" })
    hl.layer_rule({ match = { namespace = "wallpaper" }, animation = "fade 50%" })
    rule({ class = "^(com\\.mojang\\.minecraft)$" }, { immediate = true })
    rule({ title = "^(Minecraft.*|CMCLIENT.*|CMClient.*)$" }, { immediate = true })
    rule({ class = "^(crankshaft)$" }, { immediate = true })
    rule({ class = "Waydroid" }, { float = true, size = "1920 1080", center = true, fullscreen = true })
    rule({ title = "^XtMapper$" }, { float = true, border_size = 0, pin = true })
    hl.layer_rule({ match = { namespace = "rofi" }, blur = true, no_anim = true })
    hl.layer_rule({ match = { namespace = "waybar" }, no_anim = true })
end
