# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Enviroment Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

envd = HYPRCURSOR_THEME,Hackneyed
envd = HYPRCURSOR_SIZE,22
envd = XCURSOR_THEME,Hackneyed
envd = XCURSOR_SIZE,22
envd = QT_CURSOR_SIZE,22
envd = QT_STYLE_OVERRIDE,kvantum
env = LIBVA_DRIVER_NAME, nvidia
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
